# Generated by Django 6.0.5 on 2026-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoLinea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'edo_linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaLinea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
                ('estado_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('estado_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('total_estaciones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_lineas',
                'managed': False,
            },
        ),
    ]
