# Generated by Django 6.0.5 on 2026-07-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaEstacion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
                ('linea_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('linea_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('total_empleados', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_estaciones',
                'managed': False,
            },
        ),
    ]
