# Generated by Django 6.0.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0002_vistaestacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLinea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'tipo_linea',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='linea',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column='tipo', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='lineas.tipolinea'),
        ),
        migrations.AddField(
            model_name='vistalinea',
            name='tipo_codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='vistalinea',
            name='tipo_nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
