# Generated by Django 6.0.5 on 2026-07-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoProduccion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'edo_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'modelo_laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('cant_planificada', models.IntegerField(blank=True, default=0, null=True)),
                ('cant_producida', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'orden_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paro',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaOrdenProduccion',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('modelo_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('modelo_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('cant_planificada', models.IntegerField(blank=True, null=True)),
                ('cant_producida', models.IntegerField(blank=True, null=True)),
                ('estado_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('estado_nombre', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'vista_ordenes_produccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaParo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('razon', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('linea_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('linea_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('abierto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vista_paros',
                'managed': False,
            },
        ),
    ]
