# Generated by Django 6.0.5 on 2026-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdoLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'edo_laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lote_laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroEnsamblaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_ensamblaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaLaptop',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('orden_folio', models.IntegerField(blank=True, null=True)),
                ('modelo_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('modelo_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('estado_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('estado_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('linea_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('linea_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('lote_codigo', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'vista_laptops',
                'managed': False,
            },
        ),
    ]
