"""
Django settings for Client project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ob*!ktbw$zun7-xvi6h8hbr+b-)!0z_($6x674jl&)gb_=7gg&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']

# Cuando compartimos el Client por un túnel de Cloudflare, el navegador del
# compañero entra por https pero el túnel nos entrega la petición por http.
# Django compara el Origin (https://...) contra el esquema que ve aquí (http)
# y rechazaría todos los POST con "Origin checking failed". Declarar el dominio
# del túnel como de confianza resuelve eso; en local no cambia nada.
CSRF_TRUSTED_ORIGINS = [
    'https://*.trycloudflare.com',
]

# Cliente y API corren en el mismo host (127.0.0.1) y las cookies no distinguen
# puerto, así que con los nombres por defecto cada proyecto le pisaba la sesión
# al otro. Con nombres propios cada uno conserva la suya.
SESSION_COOKIE_NAME = 'client_sessionid'
CSRF_COOKIE_NAME = 'client_csrftoken'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Compartido por los tres paneles.
    'core',
    'home',

    # Un panel por rol. Cada uno es dueño de sus vistas, sus URLs y sus
    # plantillas, para que los tres se puedan trabajar en paralelo.
    'panel_admin',
    'panel_calidad',
    'panel_supervisor',

    # Pantallas del panel de administrador (ya estaban cuando el cliente era
    # uno solo, así que se quedaron en su lugar).
    'usuarios',
    'lineas',
    'produccion',
    'componentes',
    'calidad',
    'embalaje',
    'trazabilidad',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Client.middleware.MantenimientoMiddleware',

    # Va al final: necesita sesión y mensajes ya montados para poder decidir
    # y para poder avisar por qué te sacó.
    'core.middleware.AccesoPorRolMiddleware',
]

ROOT_URLCONF = 'Client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Ruta absoluta: con 'templates' a secas, Django sólo encontraba las
        # plantillas si el proceso se levantaba justo desde esta carpeta.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.sesion',
            ],
        },
    },
]

WSGI_APPLICATION = 'Client.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Aquí es donde Django juntará todos los archivos cuando ejecutes collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Opcional: Activa la compresión y caché para que tu sistema cargue rapidísimo
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Añádelo al final de settings.py
MAINTENANCE_PATHS = [
    '/perfil/',
    '/reportes/'
    
    

]