# Generated by Django 6.0.5 on 2026-07-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(blank=True, max_length=18, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdoComponente',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'edo_componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteComp',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'lote_comp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloComponente',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'modelo_componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenMaterial',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoComp',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipo_comp',
                'managed': False,
            },
        ),
    ]
