# Generated by Django 6.0.5 on 2026-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloLaptopComponente',
            fields=[
                ('pk', models.CompositePrimaryKey('modelo_laptop', 'modelo_componente', blank=True, editable=False, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'modelo_laptop_componente',
                'managed': False,
            },
        ),
    ]
