# Generated by Django 6.0.5 on 2026-07-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoEstacion',
            fields=[
                ('pk', models.CompositePrimaryKey('empleado', 'estacion', 'fecha_inicio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado_estacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoLinea',
            fields=[
                ('pk', models.CompositePrimaryKey('empleado', 'linea', 'fecha_inicio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado_linea',
                'managed': False,
            },
        ),
    ]
