# Generated by Django 6.0.5 on 2026-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empleadoestacion_empleadolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaEmpleado',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=116, null=True)),
                ('rol_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('rol_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('turno_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('turno_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('usuario', models.CharField(blank=True, max_length=32, null=True)),
                ('estado_usuario', models.CharField(blank=True, max_length=11, null=True)),
                ('estado_empleado', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'vista_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaUsuario',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=32, null=True)),
                ('empleado_numero', models.IntegerField(blank=True, null=True)),
                ('empleado_nombre', models.CharField(blank=True, max_length=116, null=True)),
                ('rol_nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('estado_usuario', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'vista_usuarios',
                'managed': False,
            },
        ),
    ]
