# Generated by Django 6.0.5 on 2026-07-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoComponente',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'edo_componente',
            },
        ),
        migrations.CreateModel(
            name='EdoLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'edo_laptop',
            },
        ),
        migrations.CreateModel(
            name='EdoLinea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'edo_linea',
            },
        ),
        migrations.CreateModel(
            name='EdoProduccion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'edo_produccion',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=50)),
                ('primerApell', models.CharField(max_length=32)),
                ('segundoApell', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='LoteComp',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'lote_comp',
            },
        ),
        migrations.CreateModel(
            name='LoteLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'lote_laptop',
            },
        ),
        migrations.CreateModel(
            name='ModeloComponente',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'modelo_componente',
            },
        ),
        migrations.CreateModel(
            name='ModeloLaptop',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'modelo_laptop',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=130)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoComp',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tipo_comp',
            },
        ),
        migrations.CreateModel(
            name='TipoEmbalaje',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tipo_embalaje',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion', models.CharField(max_length=32)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edolinea')),
            ],
            options={
                'db_table': 'linea',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edolaptop')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lotelaptop')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelolaptop')),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
        migrations.CreateModel(
            name='InspeccionCalidad',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.BooleanField()),
                ('observaciones', models.CharField(max_length=256)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laptop')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'inspeccion_calidad',
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.CharField(max_length=64)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'estacion',
            },
        ),
        migrations.CreateModel(
            name='OrdenMaterial',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'orden_material',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_planificada', models.IntegerField(default=0)),
                ('cantidad_producida', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edoproduccion')),
                ('modelo_laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelolaptop')),
            ],
            options={
                'db_table': 'orden_produccion',
            },
        ),
        migrations.AddField(
            model_name='laptop',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordenproduccion'),
        ),
        migrations.CreateModel(
            name='Paro',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.CharField(max_length=256)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'paro',
            },
        ),
        migrations.CreateModel(
            name='RegistroEnsamblaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laptop')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'registro_ensamblaje',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=18)),
                ('descripcion', models.CharField(max_length=256)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.edocomponente')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lotecomp')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelocomponente')),
                ('orden_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordenmaterial')),
                ('registro_ensamblaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.registroensamblaje')),
            ],
            options={
                'db_table': 'componente',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol'),
        ),
        migrations.AddField(
            model_name='modelocomponente',
            name='tipo_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocomp'),
        ),
        migrations.CreateModel(
            name='RegistroEmbalaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laptop')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoembalaje')),
            ],
            options={
                'db_table': 'registro_embalaje',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=32, unique=True)),
                ('contrasena', models.CharField(max_length=32)),
                ('estado', models.BooleanField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estacion')),
            ],
            options={
                'db_table': 'empleado_estacion',
                'unique_together': {('empleado', 'estacion', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='EmpleadoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.linea')),
            ],
            options={
                'db_table': 'empleado_linea',
                'unique_together': {('empleado', 'linea', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='DetalleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelocomponente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordenmaterial')),
            ],
            options={
                'db_table': 'detalle_material',
                'unique_together': {('orden', 'modelo')},
            },
        ),
    ]
