# Generated by Django 6.0.5 on 2026-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmbalaje',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_embalaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmbalaje',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'db_table': 'tipo_embalaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaRegistroEmbalaje',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('laptop_numero', models.IntegerField(blank=True, null=True)),
                ('laptop_num_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('tipo_nombre', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'vista_registro_embalaje',
                'managed': False,
            },
        ),
    ]
