# Generated by Django 6.0.5 on 2026-07-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionCalidad',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.IntegerField(blank=True, choices=[(1, 'Aprobada'), (0, 'Rechazada'), (2, 'Continuar ensamblaje')], null=True)),
                ('observaciones', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspeccion_calidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaInspeccionCalidad',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('resultado', models.IntegerField(blank=True, null=True)),
                ('resultado_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=256, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('laptop_numero', models.IntegerField(blank=True, null=True)),
                ('empleado_id', models.IntegerField(blank=True, null=True)),
                ('empleado_nombre', models.CharField(blank=True, max_length=256, null=True)),
                ('linea_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vista_inspeccion_calidad',
                'managed': False,
            },
        ),
    ]
