# Generated by Django 6.0.5 on 2026-08-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('pk', models.CompositePrimaryKey('inspeccion', 'componente', blank=True, editable=False, primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'detalle_inspeccion',
                'managed': False,
            },
        ),
    ]
